[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/', 
    '@solmate=lib/solmate/src/']

fs_permissions = [{ access = "read", path = "./broadcast" }]


[fuzz]
runs = 256 ## number of random different request ids foundry will generate to try to find a crash 
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
